# Generated by Django 5.2.17 on 2026-09-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HR_HIGH', 'Heart rate too high'), ('NO_HR', 'No heart rate'), ('DEVICE_FAULT', 'Device fault')], max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('IN_USE', 'In use'), ('OFFLINE', 'Offline'), ('OUT_OF_ORDER', 'Out of order')], default='OFFLINE', max_length=20)),
                ('firmware', models.CharField(blank=True, max_length=40)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('total_hours', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('hours_since_service', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('needs_service', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['serial'],
            },
        ),
    ]
