# Generated by Django 5.2.17 on 2026-09-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='runs.run'),
        ),
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='gym.device'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', 'type', 'acknowledged_at'], name='gym_alert_device__2ba751_idx'),
        ),
    ]
