# Generated by Django 5.2.17 on 2026-09-27 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('run_analysis', 'Run analysis')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failed_step', models.CharField(blank=True, max_length=50)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='runs.run')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pipelines.pipelinerun')),
            ],
            options={
                'ordering': ['pipeline_run', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='pipelinerun',
            index=models.Index(fields=['name', 'status', 'started_at'], name='pipelines_p_name_6fb176_idx'),
        ),
    ]
