# Generated by Django 5.2.17 on 2026-09-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('hr_rest', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hr_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goal_distance', models.PositiveIntegerField(blank=True, choices=[(5000, '5 km'), (10000, '10 km'), (21097, 'Half marathon')], null=True)),
                ('goal_time_s', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
