# Generated by Django 5.2.17 on 2026-09-27 18:47

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageHourly',
            fields=[
                ('pk', models.CompositePrimaryKey('bucket', 'run', blank=True, editable=False, primary_key=True, serialize=False)),
                ('bucket', models.DateTimeField()),
                ('seconds', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'usage_hourly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeadLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_key', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField(blank=True)),
                ('error', models.TextField()),
                ('device_serial', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('easy', 'Easy'), ('intervals', 'Intervals'), ('tempo', 'Tempo'), ('long', 'Long')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('LIVE', 'Live'), ('ANALYZING', 'Analyzing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='LIVE', max_length=20)),
                ('last_data_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='gym.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(choices=[('1K', '1 km'), ('5K', '5 km'), ('10K', '10 km')], max_length=10)),
                ('time_s', models.PositiveIntegerField()),
                ('achieved_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='runs.run')),
            ],
            options={
                'ordering': ['distance', 'time_s'],
            },
        ),
        migrations.CreateModel(
            name='RunSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.PositiveIntegerField()),
                ('duration_s', models.PositiveIntegerField()),
                ('avg_pace_s', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('zones', models.JSONField(blank=True, default=list)),
                ('splits', models.JSONField(blank=True, default=list)),
                ('trimp', models.PositiveIntegerField(default=0)),
                ('kcal', models.PositiveIntegerField(default=0)),
                ('cleaned_points', models.PositiveIntegerField(default=0)),
                ('analyzed_at', models.DateTimeField()),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='runs.run')),
            ],
            options={
                'verbose_name_plural': 'run summaries',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('time', models.DateTimeField()),
                ('hr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('speed_kmh', models.FloatField()),
                ('incline', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='runs.run')),
            ],
            options={
                'ordering': ['run', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['user', '-started_at'], name='runs_run_user_id_a9c545_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['device', 'started_at'], name='runs_run_device__a1f4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status'], name='runs_run_status_a3d5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='personalrecord',
            index=models.Index(fields=['user', 'distance', 'time_s'], name='runs_person_user_id_11eb9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='personalrecord',
            constraint=models.UniqueConstraint(fields=('run', 'distance'), name='unique_run_record'),
        ),
        migrations.AddIndex(
            model_name='sample',
            index=models.Index(fields=['run', 'time'], name='runs_sample_run_id_faafde_idx'),
        ),
        migrations.AddConstraint(
            model_name='sample',
            constraint=models.UniqueConstraint(fields=('run', 'seq', 'time'), name='unique_sample_seq'),
        ),
    ]
